### ISSUE TITLE
GitHub Pages from "docs"

### ISSUE THREAD

**Issue by jasonday** [sparanoid/almace-scaffolding#119]
GitHub Pages has an option for serving the site from a "docs" folder. Rather than the alternate GitHub Pages setup you linked, I attempted to change the destination in the config to `docs` in place of `_site` and have use GitHub Pages with minimal alterations to asme. However in doing so, the output is different than when using `_site` - extra nested directories are created:

```
-- docs
  -- lab
    -- amsf
      -- site files
```

<img width="544" alt="screen shot 2019-01-01 at 5 59 27 pm" src="https://user-images.githubusercontent.com/748011/50577173-2d9bad00-0df0-11e9-96dc-c0aeb42a79bc.png">

**Comment by jasonday** [comment]
Nevermind, I found the `baseUrl` setting and set that to `/`, which resolved the issue

**Comment by sparanoid** [comment]
@jasonday I've added a new option `flatten_base` to resolve this situation. You can also check out the [updated docs](https://sparanoid.com/lab/amsf/github-pages-setup.html), thanks!

**Comment by sparanoid** [comment]
Closing for now, feel free to reopen this issue if you still have further questions regarding this.
