### ISSUE TITLE
Can't make the link title capitalized during editing footer.html

### ISSUE THREAD

**Issue by blankymunn** [sparanoid/almace-scaffolding#126]
Hello.
First of all, I appreciate for your cool theme. I think I finally found the very theme I wanted!
I've been editing this one as I prefer, and a problem occurs.
That is, during editing footer.html, I found that I can't make the title of a link to be capitalized.
Even the default one(amsf) isn't capitalized too.
It would be kind of you to help me. The code is like this.
```html
<!-- Footer section -->
{% unless page.permalink == '/' and site.data.curtana.clean_homepage %}
    <footer class="footer">
        <ul>
            <li>
                <a href="{{ '/' | relative_url }}">{{ amsf_site_name }}</a>
            </li>
        {% if site.credits %}
            <li>
                <a href="https://github.com/blankymunn">Github</a>
           </li>
      {% endif %}
```
Thank you.

**Comment by sparanoid** [comment]
Its appearance is defined in CSS at https://github.com/sparanoid/almace-scaffolding/blob/master/_app/assets/themes/curtana/_scss/_common.scss#L840

You can customize it in https://github.com/sparanoid/almace-scaffolding/blob/master/_app/assets/_scss/_user.scss

**Comment by blankymunn** [comment]
I really appreciate your help and also I'm sorry for bothering you.
