### ISSUE TITLE
Better dark theme support

### ISSUE THREAD

**Issue by sparanoid** [sparanoid/almace-scaffolding#156]
I've added a basic dark theme support via `prefers-color-scheme: dark` media method last week, but it still has some issues:

- CSS variables (custom properties) conflict with Scss-Liquid front-matter custom CSS, aka. [Custom Color Scheme](https://sparanoid.com/lab/amsf/custom-color-scheme.html). For example: https://sparanoid.com/work/instagram-badges/
- `theme_color` and `background_color` in `manifest.json` will not work if you switch to CSS variables and no longer define custom color scheme.
- Cannot determine custom color for colored post list

**Comment by coulof** [comment]
Hi,
Is there a way to disable the dark mode? I see an option under `_app/_data/curtana.yaml` but anytime I run `grunt init` it gets erased. 

Many thanks for your sharing almace-scaffolding :-)

**Comment by sparanoid** [comment]
You don't need to run `grunt init` every time you build your site. It's just an initial step to generate essential files for your project.
