### ISSUE TITLE
Any other ways of hosting the website that can be generated automatically but not simply upload the _site folder?

### ISSUE THREAD

**Issue by KingJacM** [sparanoid/almace-scaffolding#202]
I hope I have clarified the question, excuse my broken english. I wish that the site can be deployed automatically but not uploading the _site folder manually, is there any ways that I can do that?

**Comment by sparanoid** [comment]
> can be deployed automatically

If you mean deploying automatically on GitHub. [No](https://sparanoid.com/lab/amsf/github-pages-setup.html).

If you mean on other platforms like Netlify or Vercel (formerly ZEIT). Yes.

But you need some modifications of this project in order for the server to build automatically every time you push your commits.

This project is designed for building site locally then deploying the whole static files to the remote so I don't recommend you do that.
