### ISSUE TITLE
Underline 🤔

### ISSUE THREAD

**Issue by nervouna** [sparanoid/almace-scaffolding#57]
### On Safari

![screen shot 2017-01-09 at 14 04 55](https://cloud.githubusercontent.com/assets/1436139/21758276/02dc642e-d675-11e6-9035-d64517851c25.png)

### On Chrome

![screen shot 2017-01-09 at 14 05 10](https://cloud.githubusercontent.com/assets/1436139/21758286/1194aaee-d675-11e6-9b74-8d3262a4e645.png)

**Comment by sparanoid** [comment]
Chrome 在正式支持 `text-decoration-skip` 后即可解决，暂时不想通过 border-bottom 来回避这个问题

- http://caniuse.com/#search=text-decoration-skip
- https://github.com/sparanoid/almace-scaffolding/blob/master/_app/assets/themes/curtana/_less/reset.less#L80
