### ISSUE TITLE
Github showing readme instead of site

### ISSUE THREAD

**Issue by sdhnshu** [sparanoid/almace-scaffolding#70]
I'm really sorry for this dumb question. I'm new to jekyll, grunt and github pages. I really like this theme and would like to build my portfolio website using this. I tried running everything locally and it runs fine. The only issue is when I push it to my repo, Github renders my Readme.md as my webpage. I do not how how to make it point to the index.html that it builds. 

this is my repo: https://github.com/sdhnshu/sdhnshu.github.io

Thank you in advance.

**Comment by sdhnshu** [comment]
I found a way to build it manually to html files and upload it. Seems like the only way

**Comment by sparanoid** [comment]
@sdhnshu see https://sparanoid.com/lab/amsf/github-pages-setup.html
