### ISSUE TITLE
Build Failing With Invalid Date Error

### ISSUE THREAD

**Issue by biocross** [sparanoid/almace-scaffolding#75]
I cloned the repo locally and followed the [instructions here](https://sparanoid.com/lab/amsf/getting-started.html). But the website fails to build on running `grunt serve` with the following error:

```
Running "jekyll:serve" (jekyll) task
`bundle exec jekyll build --destination _site --config _config.yml,_amsf.yml,_app/_data/curtana.yml,_config.dev.yml --drafts --future` was initiated.

Configuration file: _config.yml
Configuration file: _amsf.yml
Configuration file: _app/_data/curtana.yml
Configuration file: _config.dev.yml
            Source: _app
       Destination: _site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Invalid Date: '"\n \n \n\n \n \n \n"' is not a valid datetime. in /_layouts/default.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Date: '"\n \n \n\n \n \n \n"' is not a valid datetime.
Warning:   Liquid Exception: Invalid Date: '"\n \n \n\n \n \n \n"' is not a valid datetime. in /_layouts/default.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Date: '"\n \n \n\n \n \n \n"' is not a valid datetime. Use --force to continue.

Aborted due to warnings.
```
<img width="1402" alt="screen shot 2017-10-16 at 1 54 44 am" src="https://user-images.githubusercontent.com/840512/31588819-0577a9e2-b215-11e7-8bca-9464b213c97b.png">

When i build with `grunt serve --force`, I get the following error:
![screen shot 2017-10-16 at 1 53 46 am](https://user-images.githubusercontent.com/840512/31588809-e08a08aa-b214-11e7-86de-127e9d762429.png)

Is there something I'm missing here?

**Comment by tushgup** [comment]
I have a fix for this in PR #76

**Comment by biocross** [comment]
For some reason, after removing all the default posts, building, and then re-adding the posts and building solved the issue for me.

**Comment by sparanoid** [comment]
@biocross sorry for the trouble, just fixed this issue. Please run the following command to see if it works:

```shell
$ grunt theme-update
$ grunt serve
```
