### ISSUE TITLE
grunt serve seem like take forever to watch & unable to fire up website at local host.

### ISSUE THREAD

**Issue by Rezhe** [sparanoid/almace-scaffolding#80]
Super fancy framework I love that so much! 
But it is so hard to set up to me..
I fallowed the  instruction to get started with this framework, try to installing bundler and node.js on windows 10 ubuntu bash, it is no issues output but grunt serve watch seems gonna run forever, then I got into gruntfile delete the watch part of grunt serve, it works but there is nothing in my localhost, only the unlimited wait page.
Yes I uesing ubuntu bash on Windows, it’s maybe issues with that.
Wanna get help! It already took me so much times XD

**Comment by Rezhe** [comment]
[https://github.com/jekyll/jekyll/issues/6023](url)
something like this!
![7c577ea3-8b83-46c3-94a5-7ad1d2695ccd](https://user-images.githubusercontent.com/30205820/37716095-0beaf31a-2cf4-11e8-88d5-7ffec297cdfe.png)

**Comment by sparanoid** [comment]
I'm sorry I don't have any Windows machine at hand, could you please try to open http://127.0.0.1:4000/ in your browser? it seems a jekyll related issue.

**Comment by Rezhe** [comment]
Thanks for ur reply and problem solved! I try to use windows build in Ubuntu to make it happened, but after that it seems too slow to open in http://127.0.0.1:4000&432(chrome and Firefox) 1, may take 20 min to wait, is that normal?
