### ISSUE TITLE
Weird font displayed in windows 10, bug or new feature 🤣

### ISSUE THREAD

**Issue by Rezhe** [sparanoid/almace-scaffolding#91]
![capture](https://user-images.githubusercontent.com/30205820/46845568-f944c180-cda9-11e8-95b4-03b7b759af03.PNG)
Only happened on windows machine, chrome & edge.
It looks good tho.

**Comment by sparanoid** [comment]
This bug is fixed in v2.0.5 https://github.com/sparanoid/almace-scaffolding/commit/000339a85f85a69cf4c7c7894d496310ff5413ee
